### ISSUE TITLE
'corr=True' option in every 'Synthesis' network

### ISSUE THREAD

**Issue by herok97** [RenYang-home/RLVC#4]
Hello, I am studying with your code. Thank you.

In 'CNN_recurrent.py', there are several analysis networks and synthesis networks.
I'm wondering why did you use 'corr=True' option in synthesis networks and 'corr=False' option in analysis networks?

Thank you in advance.

**Comment by RenYang-home** [comment]
Hi,

These layers are borrowed from tensorflow-compression (see analysis and synthesis in https://github.com/tensorflow/compression/blob/73ff5ae0b09b02a74ca771ad272bd9223985e09e/models/bls2017.py). The define it as "corr: Boolean. If True, compute cross correlation. If False, convolution" (see https://tensorflow.github.io/compression/docs/api_docs/python/tfc/SignalConv2D.html). But I think you need to ask the authors of tensorflow-compression for more details and official comments on this issue. 

Thanks

**Comment by herok97** [comment]
Thank you for your kind reply. 👍
I'm using pytorch implementation for image compression model that uses just cross correlation only (torch.nn.Conv2d).  
I will find Why does tensorflow's implementation use both.
